name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        description: 'Name of the artifact to deploy'
    outputs:
      result:
        description: 'Result of the deployment'
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.deploy.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: List contents
        run: ls
      - name: Output Information
        run: |
          echo "Deploying..."
      - name: Set result output
        id: deploy
        run: echo "step-result=success" >> $GITHUB_OUTPUT